### ISSUE TITLE
RuntimeError: shape '[1, 14, 14, -1]' is invalid for input of size 151296 when resizing position embedding in ViT model

### ISSUE THREAD

**Issue by fldzc** [liyuke65535/Part-Aware-Transformer#13]
Hi, I encountered an issue when loading a pre-trained model in the Part-Aware-Transformer repository. Specifically, when trying to resize the position embedding in the Vision Transformer (ViT), I get the following error:
RuntimeError: shape '[1, 14, 14, -1]' is invalid for input of size 151296

The issue occurs in the following part of the code in vit_pytorch.py:
posemb_grid = posemb_grid.reshape(1, gs_old, gs_old, -1).permute(0, 3, 1, 2)

Error Traceback:
Resized position embedding from size:torch.Size([1, 198, 768]) to size: torch.Size([1, 132, 768]) with height:16 width: 8
Traceback (most recent call last):
  File "D:\Project\Part-Aware-Transformer-main\train.py", line 74, in <module>
    model = make_model(cfg, modelname=model_name, num_class=num_classes, camera_num=None, view_num=None)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Part-Aware-Transformer-main\model\make_model.py", line 345, in make_model
    model = build_part_attention_vit(num_class, cfg, __factory_LAT_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Part-Aware-Transformer-main\model\make_model.py", line 278, in __init__
    self.base.load_param(self.model_path)
  File "D:\Project\Part-Aware-Transformer-main\model\backbones\vit_pytorch.py", line 716, in load_param
    v = resize_pos_embed_part_vit(v, self.pos_embed, self.patch_embed.num_y, self.patch_embed.num_x)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\Part-Aware-Transformer-main\model\backbones\vit_pytorch.py", line 766, in resize_pos_embed_part_vit
    posemb_grid = posemb_grid.reshape(1, gs_old, gs_old, -1).permute(0, 3, 1, 2)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[1, 14, 14, -1]' is invalid for input of size 151296

**Comment by liyuke65535** [comment]
Hi, seems that there's something wrong with the patch-size.
Be sure that your image-size is [256, 128] with a stride-size=16 and a patch size=16.
