### ISSUE TITLE
Code problem

### ISSUE THREAD

**Issue by XaryWorld** [liyuke65535/Part-Aware-Transformer#2]

**Comment by XaryWorld** [comment]
Traceback (most recent call last):
  File "/home/server/file/Lijin/Code/PAT/train.py", line 110, in <module>
    do_train_dict[model_name](
  File "/home/server/file/Lijin/Code/PAT/processor/part_attention_vit_processor.py", line 116, in part_attention_vit_do_train_with_amp
    reid_loss = loss_fn(score, layerwise_global_feat[-1], target, all_posvid=all_posvid, soft_label=cfg.MODEL.SOFT_LABEL, soft_weight=cfg.MODEL.SOFT_WEIGHT, soft_lambda=cfg.MODEL.SOFT_LAMBDA)
TypeError: 'tuple' object is not callable

**Comment by XaryWorld** [comment]
Traceback (most recent call last):
  File "/home/server/file/**/Code/PAT/train.py", line 110, in <module>
    do_train_dict[model_name](
  File "/home/server/file/**/Code/PAT/processor/part_attention_vit_processor.py", line 116, in part_attention_vit_do_train_with_amp
    reid_loss = loss_fn(score, layerwise_global_feat[-1], target, all_posvid=all_posvid, soft_label=cfg.MODEL.SOFT_LABEL, soft_weight=cfg.MODEL.SOFT_WEIGHT, soft_lambda=cfg.MODEL.SOFT_LAMBDA)
TypeError: 'tuple' object is not callable

**Comment by ds-giao** [comment]
我也遇到了这个问题，原因是loss_fn返回了两个损失

**Comment by XaryWorld** [comment]
train.py line80
loss_func, _ = build_loss(cfg, num_classes=num_classes)改了下代码可以运行了

**Comment by ds-giao** [comment]
感谢
