### ISSUE TITLE
veriwild.py erro

### ISSUE THREAD

**Issue by yangjunxiu** [liyuke65535/Part-Aware-Transformer#8]
erro info:
Traceback (most recent call last):
  File "E:\Software\pytorch\pycharm\PyCharm 2023.1.2\plugins\python\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Software\pytorch\pycharm\PyCharm 2023.1.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "F:\occlusion\Part-Aware-Transformer\train.py", line 71, in <module>
    train_loader = build_reid_train_loader(cfg)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\occlusion\Part-Aware-Transformer\data\build_DG_dataloader.py", line 42, in build_reid_train_loader
    dataset = DATASET_REGISTRY.get(d)(root=_root, combineall=cfg.DATASETS.COMBINEALL)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\occlusion\Part-Aware-Transformer\data\datasets\veriwild.py", line 47, in __init__
    train = self.process_dir(self.train_list)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\occlusion\Part-Aware-Transformer\data\datasets\veriwild.py", line 64, in process_dir
    dataset.append((self.imgid2imgpath[imgid], vid, int(self.imgid2camid[imgid])))
                    ~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: '119083.jpg 0 23'
python-BaseException

hi, Sr, have you ever tried the VeRi-wild datasets on your code? it seems some errors there.

**Comment by liyuke65535** [comment]
Sorry about that.
Since we just consider person ReID, I have never tried VeRi-wild.
But based on the info you give, you are recommended to debug and check the whole data preprocess.
